/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Controller.EquipamentoController;
import Model.ClienteModel;
import Model.EquipamentoModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author senac TDS
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        PanelCliente.setVisible(false);
        PanelEquipamento.setVisible(false);

        //Cliente
        txtNome.setEditable(false);
        txtCPF.setEditable(false);
        txtTelefone.setEnabled(false);
        txtCidade.setEnabled(false);
        txtDataCriacao.setEnabled(false);

        //Equipamento
        txtTipo.setEnabled(false);
        txtCPFEquipamento.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtDefeito.setEnabled(false);
        txtPrazoEntrega.setEnabled(false);
        
        // Tabelas
        ListarClientesView();
        ListarEquipamentosView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JScrollPane();
        PanelSecundario = new javax.swing.JPanel();
        PanelCliente = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtDataCriacao = new javax.swing.JTextField();
        lblIDCliente = new javax.swing.JLabel();
        lblIDVerdadeiroCliente = new javax.swing.JLabel();
        PanelEquipamento = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblCPFEquipamento = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblDefeito = new javax.swing.JLabel();
        lblPrazoEntrega = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtCPFEquipamento = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtDefeito = new javax.swing.JTextField();
        txtPrazoEntrega = new javax.swing.JTextField();
        lblIDEquipamento = new javax.swing.JLabel();
        lblIDVerdadeiroEquipamento = new javax.swing.JLabel();
        PanelCRUD = new javax.swing.JPanel();
        btnSalvarClientes = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvarEquipamentos = new javax.swing.JToggleButton();
        PanelFiltro = new javax.swing.JPanel();
        lblCPFFiltro = new javax.swing.JLabel();
        txtCPFFiltro = new javax.swing.JTextField();
        btnFiltrarCliente = new javax.swing.JButton();
        btnFiltrarEquipamento = new javax.swing.JButton();
        PanelTabelaCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientes = new javax.swing.JTable();
        PanelTabelaEquipamento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEquipamentos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCadastroCliente = new javax.swing.JMenuItem();
        MenuCadastroEquipamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");

        PanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Cliente"));

        lblNome.setText("Nome:");

        lblCPF.setText("CPF:");

        lblTelefone.setText("Telefone:");

        lblCidade.setText("Cidade:");

        lblDataCriacao.setText("Data Criação:");

        lblIDCliente.setText("ID:");

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIDCliente)
                    .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDataCriacao)
                        .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCidade))
                            .addComponent(lblTelefone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtTelefone)
                    .addComponent(txtCPF)
                    .addComponent(txtCidade)
                    .addComponent(txtDataCriacao)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addComponent(lblIDVerdadeiroCliente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClienteLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDCliente)
                    .addComponent(lblIDVerdadeiroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCriacao)
                    .addComponent(txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Equipamento"));

        lblTipo.setText("Tipo:");

        lblMarca.setText("Marca:");

        lblCPFEquipamento.setText("CPF:");

        lblModelo.setText("Modelo:");

        lblDefeito.setText("Defeito:");

        lblPrazoEntrega.setText("Prazo de Entrega");

        lblIDEquipamento.setText("ID:");

        javax.swing.GroupLayout PanelEquipamentoLayout = new javax.swing.GroupLayout(PanelEquipamento);
        PanelEquipamento.setLayout(PanelEquipamentoLayout);
        PanelEquipamentoLayout.setHorizontalGroup(
            PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIDEquipamento)
                    .addComponent(lblTipo)
                    .addComponent(lblCPFEquipamento)
                    .addComponent(lblMarca)
                    .addComponent(lblModelo)
                    .addComponent(lblDefeito)
                    .addComponent(lblPrazoEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipo)
                    .addComponent(txtCPFEquipamento)
                    .addComponent(txtMarca)
                    .addComponent(txtModelo)
                    .addComponent(txtDefeito)
                    .addComponent(txtPrazoEntrega)
                    .addGroup(PanelEquipamentoLayout.createSequentialGroup()
                        .addComponent(lblIDVerdadeiroEquipamento)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelEquipamentoLayout.setVerticalGroup(
            PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEquipamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDEquipamento)
                    .addComponent(lblIDVerdadeiroEquipamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFEquipamento)
                    .addComponent(txtCPFEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefeito)
                    .addComponent(txtDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrazoEntrega)
                    .addComponent(txtPrazoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder("CRUD"));

        btnSalvarClientes.setText("Salvar Cli.");
        btnSalvarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClientesActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvarEquipamentos.setText("Salvar Equip.");
        btnSalvarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEquipamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCRUDLayout = new javax.swing.GroupLayout(PanelCRUD);
        PanelCRUD.setLayout(PanelCRUDLayout);
        PanelCRUDLayout.setHorizontalGroup(
            PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarEquipamentos)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelCRUDLayout.setVerticalGroup(
            PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCRUDLayout.createSequentialGroup()
                .addComponent(btnSalvarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelCRUDLayout.createSequentialGroup()
                .addGroup(PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvarEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PanelFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        lblCPFFiltro.setText("CPF:");

        btnFiltrarCliente.setText("Filtro Cli.");
        btnFiltrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarClienteActionPerformed(evt);
            }
        });

        btnFiltrarEquipamento.setText("Filtro Equip.");
        btnFiltrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFiltroLayout = new javax.swing.GroupLayout(PanelFiltro);
        PanelFiltro.setLayout(PanelFiltroLayout);
        PanelFiltroLayout.setHorizontalGroup(
            PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPFFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPFFiltro)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrarEquipamento)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelFiltroLayout.setVerticalGroup(
            PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFFiltro)
                    .addComponent(txtCPFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(PanelFiltroLayout.createSequentialGroup()
                .addGroup(PanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFiltrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnFiltrarEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelTabelaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela Clientes"));

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Cidade", "Data Criação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientesMouseClicked(evt);
            }
        });
        TableClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableClientesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableClientesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TableClientes);

        javax.swing.GroupLayout PanelTabelaClienteLayout = new javax.swing.GroupLayout(PanelTabelaCliente);
        PanelTabelaCliente.setLayout(PanelTabelaClienteLayout);
        PanelTabelaClienteLayout.setHorizontalGroup(
            PanelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        PanelTabelaClienteLayout.setVerticalGroup(
            PanelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTabelaEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela Equipamentos"));

        TableEquipamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "CPF", "Marca", "Modelo", "Defeito", "Prazo Conserto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableEquipamentos);

        javax.swing.GroupLayout PanelTabelaEquipamentoLayout = new javax.swing.GroupLayout(PanelTabelaEquipamento);
        PanelTabelaEquipamento.setLayout(PanelTabelaEquipamentoLayout);
        PanelTabelaEquipamentoLayout.setHorizontalGroup(
            PanelTabelaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelaEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PanelTabelaEquipamentoLayout.setVerticalGroup(
            PanelTabelaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTabelaEquipamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout PanelSecundarioLayout = new javax.swing.GroupLayout(PanelSecundario);
        PanelSecundario.setLayout(PanelSecundarioLayout);
        PanelSecundarioLayout.setHorizontalGroup(
            PanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCRUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTabelaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTabelaEquipamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSecundarioLayout.setVerticalGroup(
            PanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSecundarioLayout.createSequentialGroup()
                .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTabelaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPrincipal.setViewportView(PanelSecundario);

        jMenu1.setText("Menu");

        MenuCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        MenuCadastroCliente.setText("Cadastro Cliente");
        MenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastroCliente);

        MenuCadastroEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computer.png"))); // NOI18N
        MenuCadastroEquipamento.setText("Cadastro Equipamento");
        MenuCadastroEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastroEquipamentoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastroEquipamento);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteActionPerformed

        PanelEquipamento.setVisible(false);
        PanelCliente.setVisible(true);
    }//GEN-LAST:event_MenuCadastroClienteActionPerformed

    private void MenuCadastroEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroEquipamentoActionPerformed

        PanelCliente.setVisible(false);
        PanelEquipamento.setVisible(true);
    }//GEN-LAST:event_MenuCadastroEquipamentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        int valor = JOptionPane.showConfirmDialog(null,
                "Deseja realmente cancelar?",
                "Confirma Exclusão",
                JOptionPane.YES_NO_OPTION);

        if (valor == 0) {

            //Cliente
            txtNome.setEditable(false);
            txtCPF.setEditable(false);
            txtTelefone.setEnabled(false);
            txtCidade.setEnabled(false);
            txtDataCriacao.setEnabled(false);

            txtNome.setText("");
            txtCPF.setText("");
            txtTelefone.setText("");
            txtCidade.setText("");
            txtDataCriacao.setText("");

            //Equipamento
            txtTipo.setEnabled(false);
            txtCPFEquipamento.setEnabled(false);
            txtMarca.setEnabled(false);
            txtModelo.setEnabled(false);
            txtDefeito.setEnabled(false);
            txtPrazoEntrega.setEnabled(false);

            txtTipo.setText("");
            txtCPFEquipamento.setText("");
            txtMarca.setText("");
            txtModelo.setText("");
            txtDefeito.setText("");
            txtPrazoEntrega.setText("");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        //Cliente
        txtCPF.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
        txtCidade.setText("");
        txtDataCriacao.setText("");
        txtNome.setEditable(true);
        txtCPF.setEditable(true);
        txtTelefone.setEnabled(true);
        txtCidade.setEnabled(true);
        txtDataCriacao.setEnabled(true);
        txtDataCriacao.setEditable(true);
        txtCPF.setEditable(true);

        //Equipamento
        txtTipo.setText("");
        txtCPFEquipamento.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtDefeito.setText("");
        txtPrazoEntrega.setText("");
        txtTipo.setEnabled(true);
        txtCPFEquipamento.setEnabled(true);
        txtMarca.setEnabled(true);
        txtModelo.setEnabled(true);
        txtDefeito.setEnabled(true);
        txtPrazoEntrega.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFiltrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarClienteActionPerformed
        String itemPesquisa = txtCPFFiltro.getText();
        try {
            DefaultTableModel dtm = (DefaultTableModel) TableClientes.getModel();
            dtm.setRowCount(0);
            ClienteController clienteController = new ClienteController();
            
            ArrayList<ClienteModel> listaClientes = clienteController.searchCliente(itemPesquisa);
            Iterator<ClienteModel> iteratorCliente = listaClientes.iterator();
            while (iteratorCliente.hasNext()) {
                ClienteModel cliente = iteratorCliente.next();
                dtm.addRow(new Object[]{
                    cliente.getCpf(),
                    cliente.getNome(),
                    cliente.getTelefone(),
                    cliente.getCidade(),
                    cliente.getDataCriacao()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "deu merda");
        }
    }//GEN-LAST:event_btnFiltrarClienteActionPerformed

    private void btnSalvarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClientesActionPerformed

        String cpf = txtCPF.getText();
        String nome = txtNome.getText();
        String telefone = txtTelefone.getText();
        String cidade = txtCidade.getText();
        String dataCriacao = txtDataCriacao.getText();

        ClienteController novoCliente = new ClienteController();
        novoCliente.cadastrarClienteController(cpf, nome, telefone, cidade, dataCriacao);

        txtNome.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtCidade.setText("");
        txtDataCriacao.setText("");

        // fazer o View dps
        ListarClientesView();
    }//GEN-LAST:event_btnSalvarClientesActionPerformed

    private void btnSalvarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEquipamentosActionPerformed

        String cpf = txtCPFEquipamento.getText();
        String tipo = txtTipo.getText();
        String marca = txtMarca.getText();
        String modelo = txtModelo.getText();
        String TipoDefeito = txtDefeito.getText();
        String prazoEntrega = txtPrazoEntrega.getText();

        EquipamentoController novoEquipamento = new EquipamentoController();
        novoEquipamento.cadastrarEquipamentoController(modelo,marca,TipoDefeito,tipo,prazoEntrega,cpf);

        txtTipo.setText("");
        txtCPFEquipamento.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtDefeito.setText("");
        txtPrazoEntrega.setText("");

        // fazer o View dps
        ListarEquipamentosView();
    }//GEN-LAST:event_btnSalvarEquipamentosActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String cpf = txtCPF.getText();
        String nome = txtNome.getText();
        String Telefone = txtTelefone.getText();
        String cidade = txtCidade.getText();
        String dataCriacao = txtDataCriacao.getText();

        ClienteController alterarCliente = new ClienteController();
        alterarCliente.alterarCliente(cpf, nome, Telefone, cidade, dataCriacao);
        ListarClientesView();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String cpf = txtCPF.getText();
        String nome = txtNome.getText();
        String telefone = txtTelefone.getText();
        String cidade = txtCidade.getText();

        ClienteController excluirCliente = new ClienteController();
        excluirCliente.excluirCliente(cpf);
        txtCidade.setText("");
        txtTelefone.setText("");
        txtNome.setText("");
        ListarClientesView();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void TableClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableClientesKeyPressed
        String nome = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 1).toString();
        String telefone = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 2).toString();
        String cidade = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 3).toString();
        String cpfAux = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 0).toString();
        
        txtNome.setText(nome);
        txtCidade.setText(cidade);
        txtTelefone.setText(telefone);
        txtCPF.setText(cpfAux);
    }//GEN-LAST:event_TableClientesKeyPressed

    private void TableClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableClientesKeyReleased
        String nome = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 1).toString();
        String telefone = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 2).toString();
        String cidade = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 3).toString();
        String cpfAux = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 0).toString();
        
        txtNome.setText(nome);
        txtCidade.setText(cidade);
        txtTelefone.setText(telefone);
        txtCPF.setText(cpfAux);
    }//GEN-LAST:event_TableClientesKeyReleased

    private void TableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientesMouseClicked
        
        String nome = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 1).toString();
        String telefone = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 2).toString();
        String cidade = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 3).toString();
        String cpfAux = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 0).toString();
        String dataCriacao = TableClientes.getModel().getValueAt(TableClientes.getSelectedRow(), 4).toString();

        txtNome.setText(nome);
        txtCidade.setText(cidade);
        txtTelefone.setText(telefone);
        txtCPF.setText(cpfAux);
        txtDataCriacao.setText(dataCriacao);
        txtDataCriacao.setEditable(false);
        txtCPF.setEditable(false);
    }//GEN-LAST:event_TableClientesMouseClicked

    private void btnFiltrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarEquipamentoActionPerformed
        
        String itemPesquisa = txtCPFFiltro.getText();
        try {
            DefaultTableModel dtm = (DefaultTableModel) TableEquipamentos.getModel();
            dtm.setRowCount(0);
            EquipamentoController equipamentoController = new EquipamentoController();
            
            ArrayList<EquipamentoModel> listaEquipamento = equipamentoController.searchEquipamento(itemPesquisa);
            Iterator<EquipamentoModel> iteratorEquipamento = listaEquipamento.iterator();
            while (iteratorEquipamento.hasNext()) {
                EquipamentoModel equipamento = iteratorEquipamento.next();
                dtm.addRow(new Object[]{
                    equipamento.getTipo(),
                    equipamento.getModelo(),
                    equipamento.getEquipMarca(),
                    equipamento.getTipoDefeito(),
                    equipamento.getPrazoEntrega(),
                    equipamento.getCpf()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "deu merda");
        }
    }//GEN-LAST:event_btnFiltrarEquipamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    void ListarClientesView() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) TableClientes.getModel();
            dtm.setRowCount(0);
            ClienteController clienteController = new ClienteController();

            ArrayList<ClienteModel> listaCliente = clienteController.listarClientesController();

            Iterator<ClienteModel> iterator = listaCliente.iterator();
            while (iterator.hasNext()) {
                ClienteModel cliente = iterator.next();
                dtm.addRow(new Object[]{
                    cliente.getCpf(),
                    cliente.getNome(),
                    cliente.getTelefone(),
                    cliente.getCidade(),
                    cliente.getDataCriacao()
                });
            }

        } catch (Exception e) {
        }
    }
        void ListarEquipamentosView() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) TableEquipamentos.getModel();
            dtm.setRowCount(0);
            EquipamentoController EquipamentoController = new EquipamentoController();

            ArrayList<EquipamentoModel> listaEquipamento = EquipamentoController.listarEquipamentosController();

            Iterator<EquipamentoModel> iterator = listaEquipamento.iterator();
            while (iterator.hasNext()) {
                EquipamentoModel equip = iterator.next();
                dtm.addRow(new Object[]{
                    equip.getId(),
                    equip.getModelo(),
                    equip.getEquipMarca(),
                    equip.getTipoDefeito(),
                    equip.getPrazoEntrega(),
                    equip.getCpf()
                });
            }

        } catch (Exception e) {
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadastroCliente;
    private javax.swing.JMenuItem MenuCadastroEquipamento;
    private javax.swing.JPanel PanelCRUD;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelEquipamento;
    private javax.swing.JPanel PanelFiltro;
    private javax.swing.JScrollPane PanelPrincipal;
    private javax.swing.JPanel PanelSecundario;
    private javax.swing.JPanel PanelTabelaCliente;
    private javax.swing.JPanel PanelTabelaEquipamento;
    private javax.swing.JTable TableClientes;
    private javax.swing.JTable TableEquipamentos;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrarCliente;
    private javax.swing.JButton btnFiltrarEquipamento;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvarClientes;
    private javax.swing.JToggleButton btnSalvarEquipamentos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPFEquipamento;
    private javax.swing.JLabel lblCPFFiltro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblDefeito;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JLabel lblIDEquipamento;
    private javax.swing.JLabel lblIDVerdadeiroCliente;
    private javax.swing.JLabel lblIDVerdadeiroEquipamento;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrazoEntrega;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFEquipamento;
    private javax.swing.JTextField txtCPFFiltro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDataCriacao;
    private javax.swing.JTextField txtDefeito;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrazoEntrega;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
